### ISSUE TITLE
Adjust punctuation dot size

### ISSUE THREAD

**Issue by lynn** [toaq/Iosevka#2]
For example in monospace 900 weight they end up overlapping like this:

![image](https://github.com/user-attachments/assets/621b1f61-19c2-406e-bc18-8c1743b6f65b)

Meanwhile, on weight 100 we should enforce a minimum so that they aren't nearly invisible:

![image](https://github.com/user-attachments/assets/441546bf-f055-4578-92ed-4043513b2636)

**Comment by robintown** [comment]
You can see the dot size adjustment working a little more as intended in Aile and Etoile, so the overlapping presumably has something to do with the glyph width.
